### ISSUE TITLE
Jura X8C

### ISSUE THREAD

**Issue by Beorn1988** [AlexxIT/Jura#33]
I have a Jura X8C connected with Juras bluetooth adapter.
I can add the MAC but it shows up as without entities.
Coffe machine is less than 3 meters from Home assistant server.

Connects Bluetooth works just fine with other stuff much farther away so, guessing either juras own Bluetooth adapter isn't really an option here.
Or is it just because of my machine?

Since it isn't really supported, but had my hopes up it was nearly identical to other machines in that regard....

This is what I find on the Bluetooth info of the Jura when looking into scanned bluetooth devices in Home Assistant.

{"name":"TT214H BlueFrog","address":"C3:FB:17:2A:EC:25","rssi":-78,"manufacturer_data":{"171":"2a0508039c35921532006d33793201000000000000000000000000"},"service_data":{},"service_uuids":["00001523-0000-1000-8000-00805f9b34fb","00001623-0000-1000-8000-00805f9b34fb"],"source":"04:42:1A:59:D1:F9","connectable":true,"time":1739925492.70895,"tx_power":null}

**Comment by AlexxIT** [comment]
Check latest master version. Should be fixed.

**Comment by Beorn1988** [comment]
Tested after your changes. 
Also making sure that when looking in file editor on my home assistant that the components in core and I see them as last edited 17/2 2025 


I still get this when logging:
Logger: homeassistant.components.bluetooth.manager
Källa: components/bluetooth/manager.py:213
integration: Bluetooth ([dokumentation](https://www.home-assistant.io/integrations/bluetooth), [ärenden](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+bluetooth%22))
Inträffade först: 12:31:58 (2 händelser)
Senast loggade: 12:34:55

Error in bluetooth callback
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/bluetooth/manager.py", line 213, in async_register_callback
    callback(service_info, BluetoothChange.ADVERTISEMENT)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jura/__init__.py", line 30, in update_ble
    machine = get_machine(service_info.advertisement.manufacturer_data[171])
  File "/config/custom_components/jura/core/device.py", line 214, in get_machine
    filename = next(
        i.filename
        for i in f.filelist
        if i.filename.startswith(dirname) and i.filename.endswith(".xml")
    )
StopIteration


My Bluetooth adapter is asus BT500 from supported adapters on home assistant page. And I took the home assistant and placed it (elitedesk server) next to the coffee machine just to be sure.

**Comment by AlexxIT** [comment]
Are you sure you have tested latest master version?

**Comment by Beorn1988** [comment]
Yes, and my log shows that it has issues with line 213 and line 214.
Which is the ones updated in last master yes?

//Björn

**Comment by AlexxIT** [comment]
Line 213 in `/config/custom_components/jura/core/device.py` has been updated.
I don't see its contents in your logs. So you can still try the old version.

**Comment by Beorn1988** [comment]
Alexx!!!! Loktar ogar my friend.....

Didn't work until I rebooted entire proxmox...... the files somehow even though I downloaded and replaced didnt stick until now....

Now I have the machine in Home assistant :D

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/Jura/releases/tag/v1.1.1
